version: '2'

services:

  # Backend
  # Mounts the app as a volume and installs packages so we can develop locally
  backend:
    build: ./backend
    volumes:
      - ./backend:/src/app
    working_dir: /src/app
    command: bash -c "npm install && npm run start"
    ports:
     - "3001:3001"
    restart: on-failure

  # Frontend
  # Mounts the app as a volume and installs packages so we can develop locally
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/app:/src/app
      - ./frontend/package.json:/src/package.json
      - ./frontend/.babelrc:/src/.babelrc
    ports:
      - "3010:3010"
    command: bash -c "npm install && npm run start-dev"
    restart: on-failure
